<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        truncateTables('languages');

        $languages = [
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ace'         , 'name' => 'Achinese', 'native' => 'Aceh'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'af'          , 'name' => 'Afrikaans', 'native' => 'Afrikaans'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'agq'         , 'name' => 'Aghem', 'native' => 'Aghem'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ak'          , 'name' => 'Akan', 'native' => 'Akan'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'an'          , 'name' => 'Aragonese', 'native' => 'aragonés'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'cch'         , 'name' => 'Atsam', 'native' => 'Atsam'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'gn'          , 'name' => 'Guaraní', 'native' => 'Avañe’ẽ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ae'          , 'name' => 'Avestan', 'native' => 'avesta'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ay'          , 'name' => 'Aymara', 'native' => 'aymar aru'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'az'          , 'name' => 'Azerbaijani (Latin)', 'native' => 'azərbaycanca'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'id'          , 'name' => 'Indonesian', 'native' => 'Bahasa Indonesia'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ms'          , 'name' => 'Malay', 'native' => 'Bahasa Melayu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bm'          , 'name' => 'Bambara', 'native' => 'bamanakan'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'jv'          , 'name' => 'Javanese (Latin)', 'native' => 'Basa Jawa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'su'          , 'name' => 'Sundanese', 'native' => 'Basa Sunda'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bh'          , 'name' => 'Bihari', 'native' => 'Bihari'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bi'          , 'name' => 'Bislama', 'native' => 'Bislama'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nb'          , 'name' => 'Norwegian Bokmål', 'native' => 'Bokmål'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bs'          , 'name' => 'Bosnian', 'native' => 'bosanski'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'br'          , 'name' => 'Breton', 'native' => 'brezhoneg'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ca'          , 'name' => 'Catalan', 'native' => 'català'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ch'          , 'name' => 'Chamorro', 'native' => 'Chamoru'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ny'          , 'name' => 'Chewa', 'native' => 'chiCheŵa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kde'         , 'name' => 'Makonde', 'native' => 'Chimakonde'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sn'          , 'name' => 'Shona', 'native' => 'chiShona'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'co'          , 'name' => 'Corsican', 'native' => 'corsu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'cy'          , 'name' => 'Welsh', 'native' => 'Cymraeg'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'da'          , 'name' => 'Danish', 'native' => 'dansk'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'se'          , 'name' => 'Northern Sami', 'native' => 'davvisámegiella'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'de'          , 'name' => 'German', 'native' => 'Deutsch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'luo'         , 'name' => 'Luo', 'native' => 'Dholuo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nv'          , 'name' => 'Navajo', 'native' => 'Diné bizaad'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'dua'         , 'name' => 'Duala', 'native' => 'duálá'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'et'          , 'name' => 'Estonian', 'native' => 'eesti'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'na'          , 'name' => 'Nauru', 'native' => 'Ekakairũ Naoero'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'guz'         , 'name' => 'Ekegusii', 'native' => 'Ekegusii'],
                ['active' => true,  'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'en'          , 'name' => 'English', 'native' => 'English'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'en-AU'       , 'name' => 'Australian English', 'native' => 'Australian English'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'en-GB'       , 'name' => 'British English', 'native' => 'British English'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'en-CA'       , 'name' => 'Canadian English', 'native' => 'Canadian English'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'en-US'       , 'name' => 'U.S. English', 'native' => 'U.S. English'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' =>  'es'         , 'name' => 'Spanish', 'native' => 'español'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'eo'          , 'name' => 'Esperanto', 'native' => 'esperanto'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'eu'          , 'name' => 'Basque', 'native' => 'euskara'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ewo'         , 'name' => 'Ewondo', 'native' => 'ewondo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ee'          , 'name' => 'Ewe', 'native' => 'eʋegbe'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fil'         , 'name' => 'Filipino', 'native' => 'Filipino'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fr'          , 'name' => 'French', 'native' => 'français'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fr-CA'       , 'name' => 'Canadian French', 'native' => 'français canadien'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fy'          , 'name' => 'Western Frisian', 'native' => 'frysk'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fur'         , 'name' => 'Friulian', 'native' => 'furlan'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fo'          , 'name' => 'Faroese', 'native' => 'føroyskt'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'gaa'         , 'name' => 'Ga', 'native' => 'Ga'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ga'          , 'name' => 'Irish', 'native' => 'Gaeilge'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'gv'          , 'name' => 'Manx', 'native' => 'Gaelg'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sm'          , 'name' => 'Samoan', 'native' => 'Gagana fa’a Sāmoa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'gl'          , 'name' => 'Galician', 'native' => 'galego'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ki'          , 'name' => 'Kikuyu', 'native' => 'Gikuyu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'gd'          , 'name' => 'Scottish Gaelic', 'native' => 'Gàidhlig'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ha'          , 'name' => 'Hausa', 'native' => 'Hausa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bez'         , 'name' => 'Bena', 'native' => 'Hibena'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ho'          , 'name' => 'Hiri Motu', 'native' => 'Hiri Motu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'hr'          , 'name' => 'Croatian', 'native' => 'hrvatski'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bem'         , 'name' => 'Bemba', 'native' => 'Ichibemba'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'io'          , 'name' => 'Ido', 'native' => 'Ido'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ig'          , 'name' => 'Igbo', 'native' => 'Igbo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'rn'          , 'name' => 'Rundi', 'native' => 'Ikirundi'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ia'          , 'name' => 'Interlingua', 'native' => 'interlingua'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'iu-Latn'     , 'name' => 'Inuktitut (Latin)', 'native' => 'Inuktitut'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sbp'         , 'name' => 'Sileibi', 'native' => 'Ishisangu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nd'          , 'name' => 'North Ndebele', 'native' => 'isiNdebele'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nr'          , 'name' => 'South Ndebele', 'native' => 'isiNdebele'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'xh'          , 'name' => 'Xhosa', 'native' => 'isiXhosa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'zu'          , 'name' => 'Zulu', 'native' => 'isiZulu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'it'          , 'name' => 'Italian', 'native' => 'italiano'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ik'          , 'name' => 'Inupiaq', 'native' => 'Iñupiaq'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'dyo'         , 'name' => 'Jola-Fonyi', 'native' => 'joola'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kea'         , 'name' => 'Kabuverdianu', 'native' => 'kabuverdianu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kaj'         , 'name' => 'Jju', 'native' => 'Kaje'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mh'          , 'name' => 'Marshallese', 'native' => 'Kajin M̧ajeļ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kl'          , 'name' => 'Kalaallisut', 'native' => 'kalaallisut'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kln'         , 'name' => 'Kalenjin', 'native' => 'Kalenjin'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kr'          , 'name' => 'Kanuri', 'native' => 'Kanuri'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kcg'         , 'name' => 'Tyap', 'native' => 'Katab'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kw'          , 'name' => 'Cornish', 'native' => 'kernewek'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'naq'         , 'name' => 'Nama', 'native' => 'Khoekhoegowab'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'rof'         , 'name' => 'Rombo', 'native' => 'Kihorombo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kam'         , 'name' => 'Kamba', 'native' => 'Kikamba'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kg'          , 'name' => 'Kongo', 'native' => 'Kikongo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'jmc'         , 'name' => 'Machame', 'native' => 'Kimachame'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'rw'          , 'name' => 'Kinyarwanda', 'native' => 'Kinyarwanda'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'asa'         , 'name' => 'Kipare', 'native' => 'Kipare'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'rwk'         , 'name' => 'Rwa', 'native' => 'Kiruwa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'saq'         , 'name' => 'Samburu', 'native' => 'Kisampur'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ksb'         , 'name' => 'Shambala', 'native' => 'Kishambaa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'swc'         , 'name' => 'Congo Swahili', 'native' => 'Kiswahili ya Kongo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sw'          , 'name' => 'Swahili', 'native' => 'Kiswahili'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'dav'         , 'name' => 'Dawida', 'native' => 'Kitaita'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'teo'         , 'name' => 'Teso', 'native' => 'Kiteso'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'khq'         , 'name' => 'Koyra Chiini', 'native' => 'Koyra ciini'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ses'         , 'name' => 'Songhay', 'native' => 'Koyraboro senni'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mfe'         , 'name' => 'Morisyen', 'native' => 'kreol morisien'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ht'          , 'name' => 'Haitian', 'native' => 'Kreyòl ayisyen'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kj'          , 'name' => 'Kuanyama', 'native' => 'Kwanyama'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ksh'         , 'name' => 'Kölsch', 'native' => 'Kölsch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ebu'         , 'name' => 'Kiembu', 'native' => 'Kĩembu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mer'         , 'name' => 'Kimîîru', 'native' => 'Kĩmĩrũ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lag'         , 'name' => 'Langi', 'native' => 'Kɨlaangi'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lah'         , 'name' => 'Lahnda', 'native' => 'Lahnda'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'la'          , 'name' => 'Latin', 'native' => 'latine'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lv'          , 'name' => 'Latvian', 'native' => 'latviešu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'to'          , 'name' => 'Tongan', 'native' => 'lea fakatonga'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lt'          , 'name' => 'Lithuanian', 'native' => 'lietuvių'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'li'          , 'name' => 'Limburgish', 'native' => 'Limburgs'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ln'          , 'name' => 'Lingala', 'native' => 'lingála'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lg'          , 'name' => 'Ganda', 'native' => 'Luganda'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'luy'         , 'name' => 'Oluluyia', 'native' => 'Luluhia'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lb'          , 'name' => 'Luxembourgish', 'native' => 'Lëtzebuergesch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'hu'          , 'name' => 'Hungarian', 'native' => 'magyar'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mgh'         , 'name' => 'Makhuwa-Meetto', 'native' => 'Makua'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mg'          , 'name' => 'Malagasy', 'native' => 'Malagasy'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mt'          , 'name' => 'Maltese', 'native' => 'Malti'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mtr'         , 'name' => 'Mewari', 'native' => 'Mewari'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mua'         , 'name' => 'Mundang', 'native' => 'Mundang'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mi'          , 'name' => 'Māori', 'native' => 'Māori'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nl'          , 'name' => 'Dutch', 'native' => 'Nederlands'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nmg'         , 'name' => 'Kwasio', 'native' => 'ngumba'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'yav'         , 'name' => 'Yangben', 'native' => 'nuasue'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nn'          , 'name' => 'Norwegian Nynorsk', 'native' => 'nynorsk'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'oc'          , 'name' => 'Occitan', 'native' => 'occitan'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ang'         , 'name' => 'Old English', 'native' => 'Old English'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'xog'         , 'name' => 'Soga', 'native' => 'Olusoga'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'om'          , 'name' => 'Oromo', 'native' => 'Oromoo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ng'          , 'name' => 'Ndonga', 'native' => 'OshiNdonga'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'hz'          , 'name' => 'Herero', 'native' => 'Otjiherero'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'uz-Latn'     , 'name' => 'Uzbek (Latin)', 'native' => 'oʼzbekcha'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nds'         , 'name' => 'Low German', 'native' => 'Plattdüütsch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'pl'          , 'name' => 'Polish', 'native' => 'polski'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'pt'          , 'name' => 'Portuguese', 'native' => 'português'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'pt-BR'       , 'name' => 'Brazilian Portuguese', 'native' => 'português do Brasil'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ff'          , 'name' => 'Fulah', 'native' => 'Pulaar'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'pi'          , 'name' => 'Pahari-Potwari', 'native' => 'Pāli'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'aa'          , 'name' => 'Afar', 'native' => 'Qafar'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ty'          , 'name' => 'Tahitian', 'native' => 'Reo Māohi'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ksf'         , 'name' => 'Bafia', 'native' => 'rikpa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ro'          , 'name' => 'Romanian', 'native' => 'română'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'cgg'         , 'name' => 'Chiga', 'native' => 'Rukiga'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'rm'          , 'name' => 'Romansh', 'native' => 'rumantsch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'qu'          , 'name' => 'Quechua', 'native' => 'Runa Simi'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nyn'         , 'name' => 'Nyankole', 'native' => 'Runyankore'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ssy'         , 'name' => 'Saho', 'native' => 'Saho'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sc'          , 'name' => 'Sardinian', 'native' => 'sardu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'de-CH'       , 'name' => 'Swiss High German', 'native' => 'Schweizer Hochdeutsch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'gsw'         , 'name' => 'Swiss German', 'native' => 'Schwiizertüütsch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'trv'         , 'name' => 'Taroko', 'native' => 'Seediq'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'seh'         , 'name' => 'Sena', 'native' => 'sena'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nso'         , 'name' => 'Northern Sotho', 'native' => 'Sesotho sa Leboa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'st'          , 'name' => 'Southern Sotho', 'native' => 'Sesotho'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tn'          , 'name' => 'Tswana', 'native' => 'Setswana'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sq'          , 'name' => 'Albanian', 'native' => 'shqip'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sid'         , 'name' => 'Sidamo', 'native' => 'Sidaamu Afo'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ss'          , 'name' => 'Swati', 'native' => 'Siswati'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sk'          , 'name' => 'Slovak', 'native' => 'slovenčina'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sl'          , 'name' => 'Slovene', 'native' => 'slovenščina'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'so'          , 'name' => 'Somali', 'native' => 'Soomaali'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sr-Latn'     , 'name' => 'Serbian (Latin)', 'native' => 'Srpski'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sh'          , 'name' => 'Serbo-Croatian', 'native' => 'srpskohrvatski'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fi'          , 'name' => 'Finnish', 'native' => 'suomi'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sv'          , 'name' => 'Swedish', 'native' => 'svenska'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sg'          , 'name' => 'Sango', 'native' => 'Sängö'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tl'          , 'name' => 'Tagalog', 'native' => 'Tagalog'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tzm-Latn'    , 'name' => 'Central Atlas Tamazight (Latin)', 'native' => 'Tamazight'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kab'         , 'name' => 'Kabyle', 'native' => 'Taqbaylit'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'twq'         , 'name' => 'Tasawaq', 'native' => 'Tasawaq senni'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'shi'         , 'name' => 'Tachelhit (Latin)', 'native' => 'Tashelhit'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'nus'         , 'name' => 'Nuer', 'native' => 'Thok Nath'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'vi'          , 'name' => 'Vietnamese', 'native' => 'Tiếng Việt'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tg-Latn'     , 'name' => 'Tajik (Latin)', 'native' => 'tojikī'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lu'          , 'name' => 'Luba-Katanga', 'native' => 'Tshiluba'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 've'          , 'name' => 'Venda', 'native' => 'Tshivenḓa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tw'          , 'name' => 'Twi', 'native' => 'Twi'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tr'          , 'name' => 'Turkish', 'native' => 'Türkçe'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ale'         , 'name' => 'Aleut', 'native' => 'Unangax tunuu'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ca-valencia' , 'name' => 'Valencian', 'native' => 'valencià'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'vai-Latn'    , 'name' => 'Vai (Latin)', 'native' => 'Viyamíĩ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'vo'          , 'name' => 'Volapük', 'native' => 'Volapük'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fj'          , 'name' => 'Fijian', 'native' => 'vosa Vakaviti'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'wa'          , 'name' => 'Walloon', 'native' => 'Walon'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'wae'         , 'name' => 'Walser', 'native' => 'Walser'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'wen'         , 'name' => 'Sorbian', 'native' => 'Wendic'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'wo'          , 'name' => 'Wolof', 'native' => 'Wolof'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ts'          , 'name' => 'Tsonga', 'native' => 'Xitsonga'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'dje'         , 'name' => 'Zarma', 'native' => 'Zarmaciine'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'yo'          , 'name' => 'Yoruba', 'native' => 'Èdè Yorùbá'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' =>  'de-AT'      , 'name' => 'Austrian German', 'native' => 'Österreichisches Deutsch'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'is'          , 'name' => 'Icelandic', 'native' => 'íslenska'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'cs'          , 'name' => 'Czech', 'native' => 'čeština'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bas'         , 'name' => 'Basa', 'native' => 'Ɓàsàa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mas'         , 'name' => 'Masai', 'native' => 'ɔl-Maa'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'haw'         , 'name' => 'Hawaiian', 'native' => 'ʻŌlelo Hawaiʻi'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'el'          , 'name' => 'Greek', 'native' => 'Ελληνικά'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'uz'          , 'name' => 'Uzbek (Cyrillic)', 'native' => 'Ўзбек'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'az-Cyrl'     , 'name' => 'Azerbaijani (Cyrillic)', 'native' => 'Азәрбајҹан'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ab'          , 'name' => 'Abkhazian', 'native' => 'Аҧсуа'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'os'          , 'name' => 'Ossetic', 'native' => 'Ирон'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ky'          , 'name' => 'Kyrgyz', 'native' => 'Кыргыз'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sr'          , 'name' => 'Serbian (Cyrillic)', 'native' => 'Српски'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'av'          , 'name' => 'Avaric', 'native' => 'авар мацӀ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ady'         , 'name' => 'Adyghe', 'native' => 'адыгэбзэ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ba'          , 'name' => 'Bashkir', 'native' => 'башҡорт теле'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'be'          , 'name' => 'Belarusian', 'native' => 'беларуская'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bg'          , 'name' => 'Bulgarian', 'native' => 'български'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kv'          , 'name' => 'Komi', 'native' => 'коми кыв'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mk'          , 'name' => 'Macedonian', 'native' => 'македонски'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mn'          , 'name' => 'Mongolian (Cyrillic)', 'native' => 'монгол'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ce'          , 'name' => 'Chechen', 'native' => 'нохчийн мотт'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ru'          , 'name' => 'Russian', 'native' => 'русский'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sah'         , 'name' => 'Yakut', 'native' => 'саха тыла'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tt'          , 'name' => 'Tatar', 'native' => 'татар теле'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tg'          , 'name' => 'Tajik (Cyrillic)', 'native' => 'тоҷикӣ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tk'          , 'name' => 'Turkmen', 'native' => 'түркменче'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'uk'          , 'name' => 'Ukrainian', 'native' => 'українська'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'cv'          , 'name' => 'Chuvash', 'native' => 'чӑваш чӗлхи'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'cu'          , 'name' => 'Church Slavic', 'native' => 'ѩзыкъ словѣньскъ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kk'          , 'name' => 'Kazakh', 'native' => 'қазақ тілі'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'hy'          , 'name' => 'Armenian', 'native' => 'Հայերեն'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'yi'          , 'name' => 'Yiddish', 'native' => 'ייִדיש'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'he'          , 'name' => 'Hebrew', 'native' => 'עברית'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ug'          , 'name' => 'Uyghur', 'native' => 'ئۇيغۇرچە'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ur'          , 'name' => 'Urdu', 'native' => 'اردو'],
                ['active' => true,  'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ar'          , 'name' => 'Arabic', 'native' => 'العربية'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'uz-Arab'     , 'name' => 'Uzbek (Arabic)', 'native' => 'اۉزبېک'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tg-Arab'     , 'name' => 'Tajik (Arabic)', 'native' => 'تاجیکی'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sd'          , 'name' => 'Sindhi', 'native' => 'سنڌي'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'fa'          , 'name' => 'Persian', 'native' => 'فارسی'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'pa-Arab'     , 'name' => 'Punjabi (Arabic)', 'native' => 'پنجاب'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ps'          , 'name' => 'Pashto', 'native' => 'پښتو'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ks'          , 'name' => 'Kashmiri (Arabic)', 'native' => 'کأشُر'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ku'          , 'name' => 'Kurdish', 'native' => 'کوردی'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'dv'          , 'name' => 'Divehi', 'native' => 'ދިވެހިބަސް'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ks-Deva'     , 'name' => 'Kashmiri (Devaganari)', 'native' => 'कॉशुर'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kok'         , 'name' => 'Konkani', 'native' => 'कोंकणी'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'doi'         , 'name' => 'Dogri', 'native' => 'डोगरी'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ne'          , 'name' => 'Nepali', 'native' => 'नेपाली'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'pra'         , 'name' => 'Prakrit', 'native' => 'प्राकृत'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'brx'         , 'name' => 'Bodo', 'native' => 'बड़ो'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bra'         , 'name' => 'Braj', 'native' => 'ब्रज भाषा'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mr'          , 'name' => 'Marathi', 'native' => 'मराठी'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mai'         , 'name' => 'Maithili', 'native' => 'मैथिली'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'raj'         , 'name' => 'Rajasthani', 'native' => 'राजस्थानी'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'sa'          , 'name' => 'Sanskrit', 'native' => 'संस्कृतम्'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'hi'          , 'name' => 'Hindi', 'native' => 'हिन्दी'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'as'          , 'name' => 'Assamese', 'native' => 'অসমীয়া'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bn'          , 'name' => 'Bengali', 'native' => 'বাংলা'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mni'         , 'name' => 'Manipuri', 'native' => 'মৈতৈ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'pa'          , 'name' => 'Punjabi (Gurmukhi)', 'native' => 'ਪੰਜਾਬੀ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'gu'          , 'name' => 'Gujarati', 'native' => 'ગુજરાતી'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'or'          , 'name' => 'Oriya', 'native' => 'ଓଡ଼ିଆ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ta'          , 'name' => 'Tamil', 'native' => 'தமிழ்'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'te'          , 'name' => 'Telugu', 'native' => 'తెలుగు'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'kn'          , 'name' => 'Kannada', 'native' => 'ಕನ್ನಡ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ml'          , 'name' => 'Malayalam', 'native' => 'മലയാളം'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'si'          , 'name' => 'Sinhala', 'native' => 'සිංහල'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'th'          , 'name' => 'Thai', 'native' => 'ไทย'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'lo'          , 'name' => 'Lao', 'native' => 'ລາວ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'bo'          , 'name' => 'Tibetan', 'native' => 'པོད་སྐད་'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'dz'          , 'name' => 'Dzongkha', 'native' => 'རྫོང་ཁ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'my'          , 'name' => 'Burmese', 'native' => 'မြန်မာဘာသာ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ka'          , 'name' => 'Georgian', 'native' => 'ქართული'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'byn'         , 'name' => 'Blin', 'native' => 'ብሊን'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tig'         , 'name' => 'Tigre', 'native' => 'ትግረ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ti'          , 'name' => 'Tigrinya', 'native' => 'ትግርኛ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'am'          , 'name' => 'Amharic', 'native' => 'አማርኛ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'wal'         , 'name' => 'Wolaytta', 'native' => 'ወላይታቱ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'chr'         , 'name' => 'Cherokee', 'native' => 'ᏣᎳᎩ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'iu'          , 'name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'native' => 'ᐃᓄᒃᑎᑐᑦ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'oj'          , 'name' => 'Ojibwa', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'cr'          , 'name' => 'Cree', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'km'          , 'name' => 'Khmer', 'native' => 'ភាសាខ្មែរ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'mn-Mong'     , 'name' => 'Mongolian (Mongolian)', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'shi-Tfng'    , 'name' => 'Tachelhit (Tifinagh)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'tzm'         , 'name' => 'Central Atlas Tamazight (Tifinagh)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'yue'         , 'name' => 'Yue', 'native' => '廣州話'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ja'          , 'name' => 'Japanese', 'native' => '日本語'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'zh'          , 'name' => 'Chinese (Simplified)', 'native' => '简体中文'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'zh-Hant'     , 'name' => 'Chinese (Traditional)', 'native' => '繁體中文'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ii'          , 'name' => 'Sichuan Yi', 'native' => 'ꆈꌠꉙ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'vai'         , 'name' => 'Vai (Vai)', 'native' => 'ꕙꔤ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'jv-Java'     , 'name' => 'Javanese (Javanese)', 'native' => 'ꦧꦱꦗꦮ'],
                ['active' => false, 'icon' => 'flag-icon flag-icon-eg', 'short_name' => 'ko'          , 'name' => 'Korean', 'native' => '한국어'],
        ];

        foreach ($languages as $language) Language::firstOrCreate($language, $language);
    }
}
