import './bootstrap';

// import '../../public/app-assets/backend/vendors/css/forms/toggle/bootstrap-switch.min.css';
// import '../../public/app-assets/backend/vendors/css/forms/toggle/switchery.min.css';
// import '../../public/app-assets/backend/vendors/css/forms/selects/select2.min.css';
// import '../../public/app-assets/backend/vendors/css/tables/datatable/datatables.min.css';
// import '../../public/app-assets/backend/vendors/css/tables/extensions/buttons.dataTables.min.css';
// import '../../public/app-assets/backend/css/plugins/forms/switch.min.css';
// import '../../public/app-assets/backend/css/core/colors/palette-switch.min.css';
// import '../../public/app-assets/backend/css/plugins/loaders/loaders.min.css';
// import '../../public/app-assets/backend/css/plugins/animate/animate.min.css';
// import '../../public/app-assets/backend/customs/css/style.css';

// import '../../public/app-assets/backend/vendors/js/vendors.min.js';
// import '../../public/app-assets/backend/vendors/js/forms/select/select2.full.min.js';
// import '../../public/app-assets/backend/vendors/js/forms/extended/maxlength/bootstrap-maxlength.js';
// import '../../public/app-assets/backend/vendors/js/forms/spinner/jquery.bootstrap-touchspin.js';
// import '../../public/app-assets/backend/vendors/js/forms/toggle/bootstrap-switch.min.js';
// import '../../public/app-assets/backend/vendors/js/forms/toggle/bootstrap-checkbox.min.js';
// import '../../public/app-assets/backend/vendors/js/forms/toggle/switchery.min.js';
// import '../../public/app-assets/backend/vendors/js/ui/headroom.min.js';
// import '../../public/app-assets/backend/vendors/js/tables/datatable/datatables.min.js';
// import '../../public/app-assets/backend/js/scripts/forms/select/form-select2.js';
// import '../../public/app-assets/backend/js/scripts/forms/input-groups.js';
// import '../../public/app-assets/backend/js/scripts/fontawesome-all.min.js';
// import '../../public/app-assets/backend/js/core/app-menu.min.js';
// import '../../public/app-assets/backend/js/core/app.min.js';
// import '../../public/app-assets/backend/js/scripts/customizer.min.js';
// import '../../public/app-assets/backend/js/scripts/forms/switch.min.js';
// import '../../public/app-assets/backend/js/scripts/popover/popover.min.js';
// import '../../public/app-assets/backend/customs/js/public-functions.js';
// import '../../public/app-assets/backend/customs/js/preview-file.js';
// import '../../public/app-assets/backend/customs/js/email-notification.js';
// import '../../public/app-assets/backend/customs/js/script.js';
// import '../../public/app-assets/backend/customs/js/check-offline.js';
// import '../../public/app-assets/backend/customs/js/lock-page.js';
// import '../../public/app-assets/backend/customs/js/search.js';