<script type="text/javascript" src="{{ assetHelper('vendors/js/vendors.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/forms/select/select2.full.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/forms/extended/maxlength/bootstrap-maxlength.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/forms/spinner/jquery.bootstrap-touchspin.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/forms/toggle/bootstrap-switch.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/forms/toggle/bootstrap-checkbox.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/forms/toggle/switchery.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/ui/headroom.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/scripts/forms/select/form-select2.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/scripts/forms/input-groups.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/scripts/fontawesome-all.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/core/app-menu.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/core/app.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/scripts/customizer.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/scripts/forms/switch.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('js/scripts/popover/popover.min.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('customs/js/public-functions.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('customs/js/preview-file.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('customs/js/email-notification.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('customs/js/script.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('customs/js/check-offline.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('customs/js/lock-page.js') }}"></script>
<script type="text/javascript" src="{{ assetHelper('customs/js/search.js') }}"></script>